# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uJr3w9p-8an_ngTVA0qkavQsbwan7oqp
"""

import streamlit as st
st.title("https://colab.research.google.com/drive/1rW9sbal-6mGMFbqyX7nbyC8lqDpmvVZz")